# Generated by Django 4.0.6 on 2022-07-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(default='eth', max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=120)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('token_schema', models.CharField(default='erc721', max_length=50)),
                ('token_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('total_supply', models.IntegerField(default=0)),
                ('init_price', models.FloatField(default=0)),
                ('payment_symbol', models.CharField(default='ETH', max_length=50)),
                ('mint_date', models.DateTimeField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=500)),
                ('uri', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=120)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('traits', models.JSONField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('owner', models.CharField(max_length=50)),
                ('mint_date', models.DateTimeField(blank=True, null=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('current_price', models.FloatField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='app.contract')),
            ],
        ),
    ]
