# Generated by Django 4.0.6 on 2022-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='item_id',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
