# Generated by Django 4.0.6 on 2022-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tx_hashes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
