# Generated by Django 4.0.6 on 2022-08-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_asset_item_id_alter_transaction_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_block',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
