# Generated by Django 4.0.6 on 2022-07-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_asset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(max_length=256)),
                ('event_name', models.CharField(max_length=50)),
                ('fr', models.CharField(max_length=42)),
                ('to', models.CharField(max_length=42)),
                ('price', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.asset')),
            ],
        ),
    ]
