# Generated by Django 4.0.6 on 2022-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('minted', models.IntegerField(default=0)),
                ('trade', models.IntegerField(default=0)),
            ],
        ),
    ]
